/* Utils */
import { getSortedPosts } from './getPosts';
import { Post } from '@/utils/types';

const sortedBookPosts: Post[] = [
  {
    meta: {
      title: 'Hardboiled & Hard Luck (1999)',
      slug: undefined,
      datePublished: undefined,
      dateEdited: 'July 27, 2024',
      postType: 'book',
      category: 'Reading this Year',
      featuredImage: undefined,
      author: 'Banana Yoshimoto',
      image: 'hardboiled-hard-luck.jpg',
      url: 'https://www.goodreads.com/book/show/50142.Hardboiled_Hard_Luck?ref=nav_sb_ss_1_11',
      excerpt: undefined,
    },
    content: '',
  },
  {
    meta: {
      title: 'Pinball, 1973 (1980)',
      slug: undefined,
      datePublished: undefined,
      dateEdited: 'July 25, 2024',
      postType: 'book',
      category: 'Reading this Year',
      featuredImage: undefined,
      author: 'Haruki Murakami',
      image: 'pinball-1973.jpg',
      url: 'https://www.goodreads.com/book/show/591978.Pinball_1973',
      excerpt: undefined,
    },
    content: '',
  },
  {
    meta: {
      title: 'Hear the Wind Sing (1979)',
      slug: undefined,
      datePublished: undefined,
      dateEdited: 'July 1, 2024',
      postType: 'book',
      category: 'Reading this Year',
      featuredImage: undefined,
      author: 'Haruki Murakami',
      image: 'hear-the-wind-sing.jpg',
      url: 'https://www.goodreads.com/book/show/226973.Hear_the_Wind_Sing',
      excerpt: undefined,
    },
    content: '',
  },
  {
    meta: {
      title: 'South of the Border, West of the Sun (1992)',
      slug: undefined,
      datePublished: undefined,
      dateEdited: 'June 28, 2024',
      postType: 'book',
      category: 'Reading this Year',
      featuredImage: undefined,
      author: 'Haruki Murakami',
      image: 'south-of-the-border.jpg',
      url: 'https://www.goodreads.com/book/show/17799.South_of_the_Border_West_of_the_Sun',
      excerpt: undefined,
    },
    content: '',
  },
  {
    meta: {
      title: 'Dead-End Memories: Stories (2003)',
      slug: undefined,
      datePublished: undefined,
      dateEdited: 'April 8, 2024',
      postType: 'book',
      category: 'Reading this Year',
      featuredImage: undefined,
      author: 'Banana Yoshimoto',
      image: 'dead-end-memories.jpg',
      url: 'https://www.goodreads.com/book/show/59892213-dead-end-memories',
      excerpt: undefined,
    },
    content: '',
  },
  {
    meta: {
      title: 'Moshi Moshi (2010)',
      slug: undefined,
      datePublished: undefined,
      dateEdited: 'March 24, 2024',
      postType: 'book',
      category: 'Reading this Year',
      featuredImage: undefined,
      author: 'Banana Yoshimoto',
      image: 'moshi-moshi.jpg',
      url: 'https://www.goodreads.com/book/show/15726091-moshi-moshi',
      excerpt: undefined,
    },
    content: '',
  },
  {
    meta: {
      title: 'Moonlight Shadow (2012)',
      slug: undefined,
      datePublished: undefined,
      dateEdited: 'February 11, 2024',
      postType: 'book',
      category: 'Reading this Year',
      featuredImage: undefined,
      author: 'Banana Yoshimoto',
      image: 'moonlight-shadow.jpg',
      url: 'https://www.goodreads.com/book/show/8043651-moonlight-shadow',
      excerpt: undefined,
    },
    content: '',
  },
  {
    meta: {
      title: 'Kitchen (1988)',
      slug: undefined,
      datePublished: undefined,
      dateEdited: 'February 9, 2024',
      postType: 'book',
      category: 'Reading this Year',
      featuredImage: undefined,
      author: 'Banana Yoshimoto',
      image: 'kitchen.jpg',
      url: 'https://www.goodreads.com/book/show/50144.Kitchen',
      excerpt: undefined,
    },
    content: '',
  },
  {
    meta: {
      title: 'The Premonition (1988)',
      slug: undefined,
      datePublished: undefined,
      dateEdited: 'February 1, 2024',
      postType: 'book',
      category: 'Reading this Year',
      featuredImage: undefined,
      author: 'Banana Yoshimoto',
      image: 'the-premonition.jpg',
      url: 'https://www.goodreads.com/book/show/90564433-the-premonition',
      excerpt: undefined,
    },
    content: '',
  },
  {
    meta: {
      title: 'Colorless Tsukuru Tazaki and His Years of Pilgrimage (2013)',
      slug: undefined,
      datePublished: undefined,
      dateEdited: 'January 16, 2024',
      postType: 'book',
      category: 'Reading this Year',
      featuredImage: undefined,
      author: 'Haruki Murakami',
      image: 'colorless-tsukuru-tazaki.jpg',
      url: 'https://www.goodreads.com/book/show/41022133-colorless-tsukuru-tazaki-and-his-years-of-pilgrimage',
      excerpt: undefined,
    },
    content: '',
  },
];

test('Should sort books correctly', () => {
  expect(getSortedPosts('book', 'Reading this Year')).toStrictEqual(
    sortedBookPosts
  );
});
